# kubectl apply -f https://raw.githubusercontent.com/WiltonCarvalho/kubernetes/refs/heads/main/nfs/nfs-client.yaml
# kubectl exec -it nfs-client-0 -- bash
# mount -t nfs -o nosuid,resvport,sec=sys,nolock nfs-server-0.nfs-server.default.svc:/ /mnt
# df -h /mnt/
# touch /mnt/nfs.txt
# umount /mnt
# sudo find /var/snap/microk8s/common/default-storage -name nfs.txt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-client
  labels:
    app: nfs-client
spec:
  selector:
    matchLabels:
      app: nfs-client
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-client
    spec:
      containers:
      - name: nfs-client
        image: nginx:stable
        command:
        - sh
        - -c
        - |
          #dnf -y install nfs-utils
          mkdir /tmp/html
          cd /tmp/html
          echo ok > index.html
          echo "#!/bin/bash" > /tmp/py.sh
          echo "set -ex" >> /tmp/py.sh
          echo "pyvenv-3.6 test_env 2>/dev/null" > /tmp/py.sh
          echo "source test_env/bin/activate" >> /tmp/py.sh
          echo "export PYTHONUNBUFFERED=1" >> /tmp/py.sh
          echo "exec python -m http.server" >> /tmp/py.sh
          chmod +x /tmp/py.sh
          ln -sf /proc/self/fd/1 /tmp/stdout.log
          ln -sf /proc/self/fd/2 /tmp/stderr.log
          >/tmp/stdout.log 2>/tmp/stderr.log exec /usr/sbin/nginx -g "daemon off;" &
          pid="$!"
          echo "[ Started PID $pid ]"
          trap "echo '[ Stopping PID $pid ]' && kill -quit $pid && wait $pid" INT TERM WINCH QUIT
          wait $pid
          return_code="$?"
          exit $return_code
        env:
        - name: TZ
          value: 'America/Sao_Paulo'
        securityContext:
          privileged: true
