# Admin password for Harbor
adminPassword: "xxxxxxxxxxxxxxxxxxxxxxx"

# Exposure type configuration
exposureType: "ingress"

# External URL for Harbor
externalURL: "https://cce-harbor.wiltoncarvalho.com"

# Ingress configuration for the core service
ingress:
  core:
    hostname: "cce-harbor.wiltoncarvalho.com"
    annotations:
      kubernetes.io/ingress.class: "nginx-private"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"  # Quoted string to ensure correct type
    tls: true
    tlsSecretName: "harbor-tls-secret"  # Name of the existing TLS secret

persistence:
  persistentVolumeClaim:
    registry:
      size: "10Gi"

# Resource preset overrides (set to 'none' to disable defaults)
certificateVolume:
  resourcesPreset: "none"
volumePermissions:
  resourcesPreset: "none"
nginx:
  resourcesPreset: "none"
portal:
  resourcesPreset: "none"
core:
  resourcesPreset: "none"
jobservice:
  resourcesPreset: "none"
registry:
  server:
    resourcesPreset: "none"
  controller:
    resourcesPreset: "none"
  relativeurls: true
trivy:
  resourcesPreset: "none"
  extraEnvVars:
    - name: "TRIVY_DB_REPOSITORY"
      value: "public.ecr.aws/aquasecurity/trivy-db"
    - name: "TRIVY_JAVA_DB_REPOSITORY"
      value: "public.ecr.aws/aquasecurity/trivy-java-db"
exporter:
  resourcesPreset: "none"
postgresql:
  primary:
    resourcesPreset: "none"
redis:
  master:
    resourcesPreset: "none"