---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  serviceName: "registry"
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-control-plane
      containers:
      - name: registry
        image: registry:3
        ports:
        - containerPort: 5000
          name: registry
        volumeMounts:
        - name: data
          mountPath: /var/lib/registry
        env:
        - name: TZ
          value: 'America/Sao_Paulo'
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    nodePort: 32000
