apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: redis-tls
  namespace: redis
  files:
  - ca.crt
  - ca.key
  - redis.crt
  - redis.key
generatorOptions:
  disableNameSuffixHash: true