apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  labels:
    app: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    workingDir: /shared
    command:
    - sh
    - -c
    - |
      # shutdown() {
      # kill -TERM "$pid"
      # wait "$pid"
      # exit 0
      # }
      # trap 'shutdown' SIGINT SIGTERM
      # sleep infinity &
      # pid=$!
      # wait "$pid"
      /kaniko/executor \
      --skip-tls-verify \
      --insecure \
      --context "/shared/buildcontext" \
      --destination "registry:5000/postfix:latest"
    volumeMounts:
    - mountPath: /shared
      name: shared
  initContainers:
  - name: init
    image: alpine/git
    workingDir: /shared
    command:
    - /bin/sh
    args:
    - -c
    - |
      set -ex
      git clone https://github.com/WiltonCarvalho/apache-php-fpm-in-docker
      mv apache-php-fpm-in-docker/postfix buildcontext
      rm -rf apache-php-fpm-in-docker
    volumeMounts:
    - mountPath: /shared
      name: shared
  volumes:
  - emptyDir: {}
    name: shared
  restartPolicy: Never
