### Build and Run
# docker-compose build --progress=plain
# docker-compose up -d
# docker-compose ps
# docker-compose logs
# curl -fsSL http://localhost:8080/version
# curl -fsSL http://localhost:8081/actuator/health
# docker-compose down
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      server_port: 8080
      management_server_port: 8081
      management_endpoints_web_exposure_include: info,health,prometheus
      management_endpoints_web_basePath: /actuator
      management_endpoint_health_probes_enabled: true
      management_endpoint_health_showDetails: always
      management_endpoint_health_group_startup_include: livenessState,ping,diskSpace,redis,db
      management_endpoint_health_group_liveness_include: livenessState,ping,diskSpace
      management_endpoint_health_group_readiness_include: readinessState,ping,diskSpace,redis,db
      management_health_defaults_enabled: false
      management_health_ping_enabled: true
      management_health_diskspace_enabled: true
      management_health_redis_enabled: true
      management_health_db_enabled: true
    volumes:
      - ./config:/app/config
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: "no"
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
      test: curl -fsSL http://127.0.0.1:8081/actuator/health
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M