apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: test-cert
  namespace: monitoring
  type: "kubernetes.io/tls"
  files:
  - tls.crt=certs/test-cert.crt
  - tls.key=certs/test-cert.key
- name: grafana-admin
  namespace: monitoring
  literals:
  - user=admin
  - password=passw0rd
generatorOptions:
  disableNameSuffixHash: true
# (
#   cd secrets
#   mkdir certs
#   echo > certs/.rnd
#   openssl req -new -newkey rsa:2048 -nodes -x509 -days 3650 \
#     -subj '/O=TestCert/CN=test.example.com' \
#     -keyout certs/test-cert.key \
#     -out certs/test-cert.crt \
#     -addext "basicConstraints=CA:FALSE" \
#     -addext "extendedKeyUsage=serverAuth,clientAuth" \
#     -addext "keyUsage=nonRepudiation,digitalSignature,keyEncipherment" \
#     -addext "subjectKeyIdentifier=hash" \
#     -addext "authorityKeyIdentifier=keyid,issuer" \
#     -addext "subjectAltName=IP:127.0.0.1,DNS:localhost"
# )

# (
#   kubectl -n monitoring create secret generic grafana-admin \
#     --from-literal=user=admin \
#     --from-literal=password=passw0rd
# )