apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: log-exec-portforward-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services/portforward"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]